### ISSUE TITLE
ps in r151032 is truncating command arguments

### ISSUE THREAD

**Issue by ptribble** [omniosorg/illumos-omnios#676] opened 2020-02-10 21:22 UTC
Andy mentioned that r151032 has the new ps.

Unfortunately it appears to be truncating long commands. The simplest way to show this is to run something like the following.

Test program:
```
# cd /usr/share/man
# more */*
```

Result in r151030:
```
# ps uaxww 549|wc
       2   10597  261237
```

Result in r151032:
```
# ps uaxww 569|wc
       2     321    4227
# ps -Fl -p 569|wc
       2     329    4276
```

It appears that it's truncating the amount of the command shown to 4k instead of showing all of it like it should (ps uaxww and ps uaxwwe is a regression, the ps -F behaviour isn't consistent with the man page).

**Comment by v-a-b** [comment] 2020-03-05 14:35
I think it's not only ps.  It seems that /proc/$pid/argv gets truncated to 4k for all processes.  On Solaris, I can see argv's much larger than 4k.

**Comment by citrus-it** [comment] 2020-03-05 19:51
> I think it's not only ps. It seems that /proc/$pid/argv gets truncated to 4k for all processes. On Solaris, I can see argv's much larger than 4k.

That's by design in illumos

https://github.com/omniosorg/illumos-omnios/commit/7304dc68d23267d6d4c1de1026af5d19dc45a287#diff-a60af6f304afc8f395489b5893108204R275

**Comment by citrus-it** [comment] 2020-03-05 20:00
I've written a fix for this and will open a PR shortly.

Fixed system (the process is owned by a different user)

```
% ./i386/ps ww 24487 | wc
       2     289    4153
% pfexec ./i386/ps ww 24487 | wc
       2   12269  296893
```

Versus r151030:

```
r151030% ps ww 1674 | wc
       2      16     136
r151030% pfexec ps ww 1674 | wc
       2   11209  274498
```

The behaviour in the non-privileged case is improved to 4K of arguments and I've restored the previous behaviour for root.

**Closed** 2020-03-06 16:53 UTC
